-- ============================================================================
-- CAMPAÑAS DE DESCUENTO PROGRAMADAS · Toscana House (F2 del facelift ForgeOS)
-- Correr en Supabase SQL Editor (rol postgres). Modelo permisivo como el resto.
-- La app las prende/apaga sola por fechas (desde <= hoy <= hasta).
-- ============================================================================

create table if not exists public.campanas_descuento (
  id          bigint generated by default as identity primary key,
  marca_id    integer not null,
  nombre      text not null default '',        -- "Pre-temporada primavera"
  pct         numeric not null default 0,      -- % de descuento
  desde       date not null,                   -- inicio (inclusive)
  hasta       date not null,                   -- fin (inclusive)
  codigos     jsonb not null default '[]'::jsonb, -- [] = toda la marca; o lista de códigos
  activa      boolean not null default true,   -- kill switch manual
  creada_por  text default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.campanas_descuento disable row level security;
grant select, insert, update, delete on public.campanas_descuento to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- realtime para que caja/admin vean campañas al instante
alter publication supabase_realtime add table public.campanas_descuento;
