-- Toscana House — libro mayor, idempotencia y feature flags

begin;
set local statement_timeout = '120s';
set local lock_timeout = '10s';

create table if not exists public.th_operaciones (
  id uuid primary key,
  tipo text not null,
  payload_hash text not null,
  estado text not null default 'procesando',
  usuario text,
  auth_id uuid,
  rol text,
  device_id text,
  client_version text,
  engine text not null default 'transactional',
  resultado jsonb,
  error_code text,
  error_message text,
  intentos integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint th_operaciones_estado_chk
    check (estado in ('procesando','confirmada','rechazada'))
);

create index if not exists th_operaciones_created_idx
  on public.th_operaciones(created_at desc);
create index if not exists th_operaciones_estado_idx
  on public.th_operaciones(estado, created_at);
create index if not exists th_operaciones_usuario_idx
  on public.th_operaciones(usuario, created_at desc);

create table if not exists public.movimientos_inventario (
  id uuid primary key default gen_random_uuid(),
  operation_id uuid not null references public.th_operaciones(id),
  line_key text not null,
  producto_id bigint not null references public.inventario(id),
  codigo text not null,
  tipo text not null,
  cantidad_delta integer not null,
  stock_antes integer not null,
  stock_despues integer not null,
  stock_inicial_antes integer,
  stock_inicial_despues integer,
  venta_id text references public.ventas(id),
  cambio_id text references public.cambios(id),
  retiro_id text references public.retiros(id),
  baja_id text references public.bajas_inventario(id),
  carga_id text references public.cargas_inventario(id),
  auditoria_id text references public.auditorias_inventario(id),
  movimiento_revertido_id uuid references public.movimientos_inventario(id),
  motivo text,
  usuario text,
  auth_id uuid,
  rol text,
  device_id text,
  client_version text,
  engine text not null default 'transactional',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint movimientos_tipo_chk check (tipo in (
    'RECEPCION','IMPORTACION','REPOSICION','VENTA','ANULACION',
    'CAMBIO_ENTRADA','CAMBIO_SALIDA','RETIRO','BAJA',
    'AJUSTE_AUDITORIA','REVERSO_CARGA','CORRECCION_ADMIN','SHADOW'
  )),
  constraint movimientos_delta_no_cero_chk check (cantidad_delta <> 0),
  constraint movimientos_stock_no_negativo_chk check (stock_antes >= 0 and stock_despues >= 0),
  constraint movimientos_ecuacion_chk check (stock_antes + cantidad_delta = stock_despues)
);

create unique index if not exists movimientos_operation_line_uidx
  on public.movimientos_inventario(operation_id, line_key);
create index if not exists movimientos_operation_idx
  on public.movimientos_inventario(operation_id);
create index if not exists movimientos_producto_created_idx
  on public.movimientos_inventario(producto_id, created_at);
create index if not exists movimientos_codigo_created_idx
  on public.movimientos_inventario(codigo, created_at);
create index if not exists movimientos_venta_idx
  on public.movimientos_inventario(venta_id) where venta_id is not null;
create index if not exists movimientos_carga_idx
  on public.movimientos_inventario(carga_id) where carga_id is not null;

create table if not exists public.th_feature_flags (
  id bigint generated by default as identity primary key,
  ambiente text not null default 'production',
  operacion text not null default '*',
  usuario text not null default '*',
  device_id text not null default '*',
  modo text not null default 'legacy',
  enabled boolean not null default true,
  updated_by text,
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint th_feature_flags_modo_chk check (modo in ('legacy','shadow','transactional')),
  constraint th_feature_flags_scope_uidx unique (ambiente, operacion, usuario, device_id)
);

insert into public.th_feature_flags
  (ambiente, operacion, usuario, device_id, modo, updated_by)
values
  ('production', '*', '*', '*', 'legacy', 'migration'),
  ('staging', '*', '*', '*', 'legacy', 'migration')
on conflict (ambiente, operacion, usuario, device_id) do nothing;

create or replace function public.th_resolver_feature_flag(
  p_ambiente text,
  p_operacion text,
  p_usuario text default '*',
  p_device_id text default '*'
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select f.modo
    from public.th_feature_flags f
    where f.enabled
      and f.ambiente in (coalesce(nullif(p_ambiente,''),'production'), '*')
      and f.operacion in (coalesce(nullif(p_operacion,''),'*'), '*')
      and f.usuario in (coalesce(nullif(p_usuario,''),'*'), '*')
      and f.device_id in (coalesce(nullif(p_device_id,''),'*'), '*')
    order by
      (f.ambiente <> '*')::int desc,
      (f.operacion <> '*')::int desc,
      (f.usuario <> '*')::int desc,
      (f.device_id <> '*')::int desc,
      f.updated_at desc
    limit 1
  ), 'legacy');
$$;

create or replace function public.th_prevenir_mutacion_movimiento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception using
    errcode = '42501',
    message = 'Los movimientos de inventario son inmutables; use un movimiento compensatorio';
end;
$$;

drop trigger if exists movimientos_inmutables on public.movimientos_inventario;
create trigger movimientos_inmutables
before update or delete on public.movimientos_inventario
for each row execute function public.th_prevenir_mutacion_movimiento();

create or replace function public.th_prevenir_delete_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception using
    errcode = '42501',
    message = 'El registro de auditoría no se puede eliminar';
end;
$$;

drop trigger if exists audit_log_no_delete on public.audit_log;
create trigger audit_log_no_delete
before delete on public.audit_log
for each row execute function public.th_prevenir_delete_audit();

revoke all on function public.th_resolver_feature_flag(text,text,text,text) from public,anon;
grant execute on function public.th_resolver_feature_flag(text,text,text,text) to authenticated,service_role;

commit;
